name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Branche à surveiller pour déclencher le workflow

  # Permet de lancer le workflow manuellement depuis l'onglet Actions
  workflow_dispatch:

# Autorisations nécessaires pour déployer sur GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Limite la concurrence pour éviter les conflits
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
